require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'
ENV['COCOAPODS_ALLOW_WARNINGS'] = 'true'
ENV['COCOAPODS_VERIFICATION_DISABLED'] = 'true'

flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'BeChill' do
  config = use_native_modules!
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false, # ✅ Hermes désactivé
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'BeChillTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)
  
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= '$(inherited)'
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] += ' -D_FMT_CHAR8_T=0'
      end
    end
  
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
  
end
